In [1]:
!pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.8.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.11/dist-packages (from category_encoders) (1.26.4)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.11/dist-packages (from category_encoders) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.11/dist-packages (from category_encoders) (1.0.1)
Requirement already satisfied: scikit-learn>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from category_encoders) (1.13.1)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from category_encoders) (0.14.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.5->category_encoders) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.5->category_encoders) (2025.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.6.0->category_encoders) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.6.0->category_encoders) (3.5.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.11/dist-packages (from statsmodels>=0.9.0->category_encoders) (24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Downloading category_encoders-2.8.0-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.7/85.7 kB 2.3 MB/s eta 0:00:00
Installing collected packages: category_encoders
Successfully installed category_encoders-2.8.0

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/usedcarpriceprediction/datasets/used_car_dataset.csv')

# Data Analysis

In [4]:
df

,car_name,car_price_in_rupees,kms_driven,fuel_type,city,year_of_manufacture
0,Hyundai Grand i10 Magna 1.2 Kappa VTVT [2017-2...,₹ 4.45 Lakh,"22,402 km",Petrol,Mumbai,2016
1,Maruti Suzuki Alto 800 Lxi,₹ 2.93 Lakh,"10,344 km",Petrol,Kolkata,2019
2,Tata Safari XZ Plus New,₹ 22.49 Lakh,"12,999 km",Diesel,Bangalore,2021
3,Maruti Suzuki Ciaz ZXI+,₹ 6.95 Lakh,"45,000 km",Petrol,Thane,2016
4,Jeep Compass Sport Plus 1.4 Petrol [2019-2020],₹ 12 Lakh,"11,193 km",Petrol,Kolkata,2019
...,...,...,...,...,...,...
2100,Ford Figo Titanium1.5 TDCi,₹ 3.6 Lakh,"42,158 km",Diesel,Kolkata,2015
2101,MINI Cooper Countryman Cooper D,₹ 22 Lakh,"68,862 km",Diesel,Hyderabad,2013
2102,Hyundai Verna 1.6 VTVT SX,₹ 8.38 Lakh,"37,622 km",Petrol,Chennai,2018
2103,Maruti Suzuki Ciaz VXi+ AT,₹ 6.75 Lakh,"64,726 km",Petrol,Mumbai,2017
2104,Hyundai Verna 1.6 VTVT SX,₹ 8.76 Lakh,"29,150 km",Petrol,Pune,2017

In [5]:
df.columns

Index(['car_name', 'car_price_in_rupees', 'kms_driven', 'fuel_type', 'city',
       'year_of_manufacture'],
      dtype='object')

In [6]:
df.size

12630

In [7]:
df.shape

(2105, 6)

# Data Processing

In [8]:
print(df['car_name'].unique())
for value in df['car_name'].unique():
  print(value)

['Hyundai Grand i10 Magna 1.2 Kappa VTVT [2017-2020]'
 'Maruti Suzuki Alto 800 Lxi' 'Tata Safari XZ Plus New'
 'Maruti Suzuki Ciaz ZXI+'
 'Jeep Compass Sport Plus 1.4 Petrol [2019-2020]'
 'Maruti Suzuki Eeco 5 STR WITH A/C+HTR [2019-2020]'
 'Hyundai Creta SX Plus 1.6 AT CRDI' 'Maruti Suzuki Ertiga VXi AT'
 'Toyota Etios Liva G' 'Renault Kwid 1.0 RXT AMT Opt [2016-2019]'
 'Maruti Suzuki Ciaz VDi+ SHVS' 'Maruti Suzuki Alto 800 LXi (O)'
 'Chevrolet Optra Magnum LS 2.0 TCDi' 'Maruti Suzuki Vitara Brezza VDi'
 'Jeep Compass Longitude 2.0 Diesel [2017-2020]'
 'Toyota Corolla Altis VL AT Petrol'
 'Hyundai Elite i20 Magna Executive 1.2' 'Mercedes-Benz EQC 400 4MATIC'
 'Ford EcoSport Titanium 1.5L Ti-VCT' 'Hyundai i10 Magna 1.2 Kappa2'
 'Hyundai Creta 1.6 SX Plus Petrol Special Edition' 'Porsche 718 Boxster'
 'Kia Seltos HTE 1.5 Diesel'
 'Maruti Suzuki Ciaz Alpha Hybrid 1.5 AT [2018-2020]'
 'Renault Kwid 1.0 RXL [2017-2019]' 'BMW 3 Series 320d Luxury Line'
 'Maruti Suzuki Baleno Alpha 1.2' 'Hyundai i20 Sportz 1.2 IVT'
 'Maruti Suzuki Wagon R 1.0 VXI' 'Honda Jazz VX Diesel'
 'Maruti Suzuki Swift VDi' 'Tata Nexon XZ Plus'
 'Audi Q3 35 TDI Premium + Sunroof'
 'Hyundai Santro Sportz CNG [2018-2020]'
 'Maruti Suzuki Alto 800 LXi (O) CNG'
 'MG Hector Plus Sharp 1.5 DCT Petrol' 'Ford Figo Duratec Petrol ZXI 1.2'
 'Audi Q3 2.0 TDI Base Grade' 'Hyundai Creta SX Plus 1.6  Petrol'
 'Honda Jazz ZX' 'Hyundai Grand i10 Asta 1.2 Kappa VTVT [2013-2016]'
 'BMW X1 sDrive20d' 'Maruti Suzuki Swift ZDi Plus'
 'BMW 5 Series 520d Luxury Line [2017-2019]' 'Skoda Superb L&K TSI AT'
 'Maruti Suzuki Swift DZire VXI' 'Maruti Suzuki Wagon R 1.0 LXI CNG'
 'Tata Tiago Revotron XZA' 'Tata Tiago Revotron XT [2016-2019]'
 'Maruti Suzuki Wagon R LXi 1.0 CNG' 'Hyundai Xcent S 1.2'
 'Kia Seltos HTK 1.5 [2020-2021]' 'BMW 5 Series 520d Luxury Line'
 'Kia Seltos HTE 1.5' 'Hyundai Creta 1.6 SX Plus AT Petrol'
 'Hyundai Grand i10 Sportz (O) 1.2 Kappa VTVT [2017-2018]'
 'Kia Seltos GTX 1.4 Dual Tone' 'Maruti Suzuki S-Presso VXi'
 'Hyundai Elite i20 Sportz 1.4' 'Mercedes-Benz GLC 200 Progressive'
 'Mercedes-Benz E-Class E 200' 'Audi A4 35 TDI Technology'
 'Chevrolet Cruze LTZ AT' 'Honda City 1.5 S MT'
 'Hyundai Elite i20 Sportz 1.2' 'Mercedes-Benz C-Class 220 BlueEfficiency'
 'Hyundai Eon Magna [2011-2012]' 'Maruti Suzuki Baleno Delta 1.2'
 'Volkswagen Vento Comfortline 1.2 (P) AT' 'Maruti Suzuki Wagon R 1.0 VXi'
 'Hyundai Venue S 1.0 Petrol [2019-2020]' 'Mercedes-Benz C-Class 200 K AT'
 'Maruti Suzuki Vitara Brezza ZDi Plus' 'Honda City VX CVT'
 'Maruti Suzuki Wagon R 1.0 VXI AMT'
 'Audi Q5 3.0 TDI quattro Premium Plus' 'Audi A6 2.0 TDI Premium'
 'Hyundai Xcent SX 1.2 (O)' 'MG Hector Sharp 2.0 Diesel [2019-2020]'
 'Maruti Suzuki Baleno Sigma 1.2' 'Maruti Suzuki S-Presso VXi Plus'
 'Maruti Suzuki Baleno Zeta 1.3'
 'Jeep Compass Limited 1.4 Petrol AT [2017-2020]'
 'Maruti Suzuki Ignis Zeta 1.2 MT'
 'Hyundai Grand i10 Sports Edition 1.2L Kappa VTVT' 'Honda City V'
 'Toyota Glanza G CVT' 'Audi Q3 2.0 TDI quattro Premium'
 'Maruti Suzuki Swift DZire ZXI' 'Renault Kwid RXT [2015-2019]'
 'Hyundai Verna Fluidic 1.6 VTVT SX'
 'Maruti Suzuki Vitara Brezza ZDi Plus AGS'
 'MG Hector Sharp 1.5 DCT Petrol [2019-2020]' 'Honda City V Diesel'
 'Maruti Suzuki Swift VXi ABS' 'Hyundai Verna Fluidic 1.6 CRDi SX'
 'Maruti Suzuki Swift ZXi' 'Ford Endeavour Titanium 3.2 4x4 AT'
 'Volvo V40 D3 Kinetic' 'Ford EcoSport Ambiente 1.5L TDCi'
 'Hyundai Xcent SX CRDi' 'Mahindra XUV500 W8' 'Hyundai Verna 1.6 VTVT SX'
 'Hyundai Grand i10 Magna 1.2 Kappa VTVT [2013-2016]'
 'Maruti Suzuki Baleno Zeta 1.2 AT' 'BMW 5 Series 530i Sport Line'
 'Maruti Suzuki Ciaz Zeta Hybrid  1.5 [2018-2020]'
 'Maruti Suzuki Ciaz Delta 1.5' 'Renault Triber RXZ EASY-R AMT'
 'Honda City SV' 'Tata Indica LS' 'Maruti Suzuki Celerio VXi AMT'
 'Honda CR-V 2.4 AT' 'Nissan Terrano XL (P)'
 'Volkswagen Ameo Highline Plus 1.5L AT (D)16 Alloy'
 'Hyundai Elite i20 Sportz 1.2 [2016-2017]'
 'Renault Kwid 1.0 RXT [2016-2019]' 'Tata Tiago JTP 1.2 [2018-2019]'
 'Maruti Suzuki Alto K10 VXi [2014-2019]' 'Tata Nexon XMA Diesel'
 'Tata Safari XTA Plus' 'Honda Jazz E MT [2015-2016]'
 'Mahindra XUV500 W11 AT' 'Audi A3 35 TDI Premium + Sunroof'
 'Volkswagen Polo GT TSI' 'Toyota Innova Crysta GX 2.4 7 STR'
 'Honda City VX CVT Petrol' 'Hyundai Santro Sportz AMT'
 'Hyundai Grand i10 Nios Sportz 1.2 Kappa VTVT'
 'Hyundai i10 1.1L iRDE Magna Special Edition' 'BMW 5 Series 520d Sedan'
 'Tata Harrier XZ Plus Dual Tone' 'BMW 7 Series 750Li Sedan'
 'Maruti Suzuki Ciaz Alpha 1.4 AT' 'Skoda Rapid Style 1.5 TDI AT'
 'Maruti Suzuki Baleno Zeta 1.2' 'Maruti Suzuki Celerio VXi AMT ABS'
 'Honda Jazz V Petrol' 'Land Rover Discovery Sport HSE 7-Seater'
 'Hyundai Creta SX 1.6 (O) Petrol'
 'Hyundai i10 1.2 L Kappa Magna Special Edition'
 'Honda City VX CVT Petrol [2017-2019]' 'Tata Hexa XTA 4x2 6 STR'
 'Hyundai Elite i20 Asta 1.2 (O) CVT [2019-2020]'
 'Skoda Octavia 2.0 TDI L&K' 'Hyundai Tucson GLS 4WD AT Diesel'
 'Maruti Suzuki Swift Dzire LDI' 'Maruti Suzuki Swift VXi'
 'Honda Amaze 1.2 EX i-VTEC' 'Renault Duster 85 PS RxL Diesel'
 'Maruti Suzuki Alto 800 Vxi' 'BMW X3 xDrive 30d M Sport [2015-2017]'
 'Mahindra TUV300 T8 AMT mHAWK100' 'Kia Carnival Prestige 7 STR'
 'Jeep Compass Limited Plus Diesel [2018-2020]'
 'Audi Q5 2.0 TDI quattro Premium' 'Hyundai Creta SX 1.6 Petrol'
 'Honda City V CVT Petrol [2017-2019]' 'Mercedes-Benz S-Class 350 CDI L'
 'Honda City ZX CVT Petrol' 'Hyundai Creta E Plus 1.6 Petrol'
 'Renault Duster 85 PS RXS 4X2 MT Diesel'
 'Renault Kwid 1.0 RXT Opt [2016-2019]' 'Toyota Glanza V'
 'Maruti Suzuki Swift VDi ABS [2014-2017]' 'Isuzu MU-X 4x2'
 'Renault Duster 85 PS RxL Diesel (Opt)'
 'Honda Amaze 1.2 VX MT Petrol [2018-2020]' 'Volvo XC90 D5 AWD'
 'Hyundai Grand i10 Asta 1.2 Kappa VTVT' 'Honda City VX' 'Toyota Glanza G'
 'Maruti Suzuki Alto K10 VXi AMT [2014-2018]' 'Honda City 1.5 V MT'
 'Mercedes-Benz E-Class E 220 d Avantgarde'
 'Audi A4 3.0 TDI quattro Technology Pack'
 'Maruti Suzuki Ciaz Alpha Hybrid 1.5 [2018-2020]'
 'Skoda Rapid Ultima Elegance 1.6 TDI CR MT' 'Honda Amaze 1.5 VX i-DTEC'
 'Kia Seltos GTX Plus AT 1.4 [2019-2020]' 'Honda Amaze 1.5 S i-DTEC'
 'Maruti Suzuki Ciaz Zeta Hybrid 1.5 AT [2018-2020]'
 'Volkswagen Vento Highline Plus 1.2 (P) AT 16 Alloy'
 'Maruti Suzuki Celerio ZXi [2017-2019]' 'Maruti Suzuki Ertiga VXI CNG'
 'Skoda Rapid Ambition 1.6 TDI CR MT' 'Tata Harrier XZ [2019-2020]'
 'Maruti Suzuki Dzire ZXi Plus AMT' 'Mahindra TUV300 T8'
 'Maruti Suzuki Alto K10 VXi' 'Audi Q3 35 TDI quattro Premium Plus'
 'Jaguar XE Portfolio Diesel' 'Toyota Innova Crysta ZX 2.4 AT 7 STR'
 'Maruti Suzuki Ciaz Delta 1.3 Diesel' 'MINI Cooper JCW Hatchback'
 'Jeep Compass Limited Plus 2.0 Diesel 4x4 AT'
 'Volkswagen Polo Comfortline 1.2L (P)' 'Maruti Suzuki Wagon R LXi Minor'
 'Maruti Suzuki Ignis Delta 1.2 MT' 'Hyundai Xcent SX 1.2'
 'Mercedes-Benz E-Class E350 CDI BlueEfficiency' 'Volvo S60 Kinetic D4'
 'Maruti Suzuki Estilo VXi ABS BS-IV' 'Hyundai i20 Asta (O) 1.2 MT'
 'Maruti Suzuki Ciaz Delta 1.4 MT'
 'Maruti Suzuki Swift VXi AMT [2018-2019]'
 'BMW 3 Series Gran Limousine 320Ld Luxury Line'
 'Ford Figo Duratec Petrol EXI 1.2' 'Audi TT 45 TFSI'
 'Maruti Suzuki Celerio ZXi AMT [2019-2020]' 'BMW X1 sDrive20d Expedition'
 'Volvo S90 D4 Inscription' 'Hyundai Creta 1.6 S Plus AT'
 'Maruti Suzuki Celerio VXi'
 'Hyundai Grand i10 Sportz 1.2 Kappa VTVT [2016-2017]'
 'Datsun redi-GO S [2016-2019]' 'Kia Seltos GTX Plus 1.4 [2020-2021]'
 'Skoda Octavia Elegance 2.0 TDI AT'
 'Maruti Suzuki Wagon R 1.0 LXI CNG (O)' 'Hyundai Eon Era +'
 'Audi Q7 45 TDI Technology Pack' 'Audi A6 35 TDI Matrix'
 'Mercedes-Benz GLS 350 d' 'Mahindra XUV500 W10'
 'Maruti Suzuki Celerio VXi AMT [2017-2019]'
 'Maruti Suzuki Wagon R 1.0 LXI' 'Hyundai Creta 1.6 S Petrol'
 'Skoda Rapid Ambition 1.6 MPI MT' 'Jaguar XF 3.0 V6 Premium Luxury'
 'Toyota Innova 2.5 G BS III 7 STR'
 'Toyota Fortuner 2.8 4x4 AT [2016-2020]' 'Maruti Suzuki Dzire VXi AMT'
 'Datsun GO T [2018-2019]' 'Ford EcoSport Titanium 1.0 Ecoboost'
 'Maruti Suzuki Ertiga Vxi' 'Mercedes-Benz CLA 200 CDI Sport'
 'Skoda Octavia 1.8 TSI L&K' 'Toyota Corolla Altis G Petrol'
 'Toyota Corolla Altis 1.8 G AT' 'Hyundai Elite i20 Asta 1.2 (O) [2016]'
 'Maruti Suzuki Swift VXi [2014-2017]'
 'Renault Kiger RXT Turbo CVT Dual Tone'
 'Hyundai Elite i20 Asta 1.4 CRDI (O) [2016-2017]' 'Porsche Cayenne Turbo'
 'Renault Kwid CLIMBER 1.0 (O)' 'Hyundai Santro Sportz'
 'Nissan Micra XV Diesel' 'Hyundai Grand i10 Magna AT 1.2 Kappa VTVT'
 'Mercedes-Benz CLA 200 Petrol Sport'
 'Land Rover Range Rover Evoque SE R-Dynamic Petrol'
 'Maruti Suzuki S-Cross Alpha 1.3'
 'Hyundai Verna SX (O) AT Anniversary Edition 1.6 VTVT'
 'Land Rover Range Rover Sport SDV6 SE' 'Hyundai Verna 1.6 VTVT SX (O)'
 'Honda Jazz V AT Petrol' 'Hyundai Creta S 1.5 Diesel [2020-2022]'
 'Honda Jazz V Diesel' 'Maruti Suzuki Alto K10 LXi'
 'Hyundai Elite i20 Asta 1.2 [2016-2017]' 'Honda City SV CVT'
 'BMW X1 sDrive20d xLine' 'Maruti Suzuki XL6 Zeta MT Petrol'
 'Mercedes-Benz GLE 350 d'
 'Ford EcoSport Titanium+ 1.5L TDCi Black Edition' 'Mahindra XUV500 W6 AT'
 'Hyundai i20 Active 1.2 S' 'Mercedes-Benz AMG GLA35 4MATIC'
 'Hyundai Elite i20 Asta 1.2' 'Hyundai Verna Fluidic 1.6 VTVT SX Opt AT'
 'Mercedes-Benz C-Class C 200 Avantgarde Edition'
 'Volkswagen Polo Highline1.2L (P)' 'Renault Kwid 1.0 RXT Opt'
 'Maruti Suzuki Dzire ZXi AMT' 'Kia Sonet GTX Plus 1.5 [2020-2021]'
 'Maruti Suzuki Ignis Sigma 1.2 MT' 'Volkswagen Vento Trendline Petrol'
 'Maruti Suzuki Alto 800 Lxi CNG' 'Ford Aspire Titanium 1.2 Ti-VCT'
 'Ford EcoSport Titanium 1.0 Ecoboost (Opt)'
 'Volkswagen Taigun GT Plus 1.5 TSI DSG'
 'Hyundai Grand i10 Asta 1.2 Kappa VTVT (O) [2013-2017]'
 'Toyota Fortuner 2.8 4x2 MT [2016-2020]'
 'Skoda Rapid Ambition 1.6 MPI AT' 'Honda City S Petrol'
 'Tata Nano Twist XT' 'Maruti Suzuki Ertiga Vxi CNG'
 'Maruti Suzuki S-Cross Zeta 1.3' 'Mahindra Thar LX Hard Top Diesel AT'
 'Land Rover Discovery Sport HSE' 'Maruti Suzuki Dzire VDi AMT'
 'Maruti Suzuki Baleno RS 1.0' 'Hyundai Venue SX 1.0 Petrol [2019-2020]'
 'Maruti Suzuki Ciaz VXi' 'Nissan Sunny XE' 'Jeep Wrangler Rubicon'
 'Maruti Suzuki Swift VXi AMT' 'Volkswagen Vento Highline 1.5 (D) AT'
 'Hyundai Elantra 1.6 SX (O) AT' 'Honda WR-V VX MT Diesel'
 'Honda BR-V VX Diesel' 'Mercedes-Benz GLA 220 d 4MATIC'
 'Tata Tiago Revotorq XZ Plus' 'Hyundai Elite i20 Asta 1.4 CRDI'
 'BMW 7 Series 760Li' 'Hyundai i20 Sportz 1.2 BS-IV'
 'Tata Tiago XZ Plus CNG' 'Tata Tiago Revotron XE [2016-2019]'
 'Tata Harrier XZA Plus' 'Honda City SV Petrol [2019-2020]'
 'Ford EcoSport Titanium 1.5L Ti-VCT AT'
 'Skoda Kushaq Style 1.5L TSI DSG (6 Airbags)'
 'Audi A4 35 TFSI Premium Sunroof' 'Nissan Magnite XE'
 'Ford EcoSport Titanium 1.5 Ti-VCT AT' 'Honda Jazz ZX CVT'
 'Land Rover Range Rover Velar 2.0 R-Dynamic Petrol 250'
 'Ford EcoSport Titanium + 1.5L TDCi'
 'BMW 3 Series GT 320d Luxury Line [2014-2016]'
 'Maruti Suzuki Swift ZXi Plus'
 'Maruti Suzuki Vitara Brezza VDi (O) [2016-2018]'
 'Hyundai Santro Sportz [2018-2020]'
 'Jeep Compass Limited (O) 2.0 Diesel 4x4 [2017-2020]'
 'Honda WR-V VX MT Petrol' 'Hyundai Elite i20 Sportz 1.4 CRDI [2016-2017]'
 'MG Hector Sharp 1.5 Petrol Turbo DCT'
 'Maruti Suzuki Alto 800 LXi CNG (O)'
 'Volkswagen Taigun Topline 1.0 TSI AT'
 'Hyundai Grand i10 Sportz (O) AT 1.2 Kappa VTVT [2017-2018]'
 'Maruti Suzuki SX4 ZXi' 'Honda Amaze 1.2 V CVT Petrol [2018-2020]'
 'Toyota Yaris V MT' 'Hyundai Creta 1.6 E Petrol'
 'Hyundai Grand i10 Era 1.1 CRDi [2016-2017]'
 'Toyota Fortuner Legender 4X2 AT 2.8 Legender' 'Toyota Etios Cross 1.2 G'
 'Ford EcoSport Titanium 1.5 TDCi'
 'Hyundai Grand i10 Magna 1.1 CRDi [2016-2017]' 'BMW X5 xDrive 30d'
 'Fiat Punto Active 1.3' 'Renault Kwid CLIMBER 1.0 AMT [2017-2019]'
 'Mercedes-Benz C-Class C 220 CDI Avantgarde'
 'Maruti Suzuki XL6 Zeta AT Petrol' 'Volkswagen Polo Comfortline 1.2L (D)'
 'Maruti Suzuki Dzire VDi' 'Maruti Suzuki Ritz VXI BS-IV'
 'Hyundai Creta SX (O) 1.5 Petrol CVT [2020-2022]'
 'Volkswagen Taigun Highline 1.0 TSI AT'
 'Toyota Innova Crysta 2.8 GX AT 7 STR [2016-2020]'
 'Maruti Suzuki Ertiga ZXi' 'Nissan Micra Active XV'
 'BMW 3 Series 330i Sport Line' 'MINI Cooper Countryman Cooper D'
 'Hyundai Verna 1.4 VTVT' 'Hyundai i20 Asta 1.2'
 'Jeep Compass Limited (O) 1.4 Petrol AT [2017-2020]'
 'Toyota Innova 2.5 G4 8 STR' 'Tata Indica V2 DLE BS-III'
 'Maruti Suzuki Baleno Zeta' 'Hyundai Elite i20 Sportz 1.2 (O)'
 'Hyundai i20 Magna 1.2' 'MG Astor Sharp 1.5 CVT'
 'Toyota Fortuner 2.8 4x2 AT [2016-2020]' 'Mercedes-Benz A-Class A 200d'
 'Toyota Fortuner 3.0 4x2 AT' 'Mercedes-Benz GLC 220 d Sport'
 'Hyundai Grand i10 Nios Sportz AMT 1.2 Kappa VTVT'
 'Toyota Innova Crysta 2.8 GX AT 8 STR [2016-2020]'
 'Toyota Innova Crysta ZX 2.4 7 STR' 'Maruti Suzuki Wagon R ZXi 1.2'
 'Honda City Anniversary Edition Diesel' 'Hyundai Elite i20  Asta 1.2 AT'
 'Mahindra Scorpio S6 Plus 1.99 Intelli-Hybrid'
 'Hyundai Elite i20 Asta 1.4 (O) CRDi' 'Renault Kwid RXL [2015-2019]'
 'Ford Figo Duratorq Diesel Titanium 1.4' 'Honda Civic 1.8V MT'
 'Mahindra XUV700 AX 7 Diesel AT 7 STR' 'Honda Brio E MT'
 'BMW 3 Series 330i M Sport Edition' 'Toyota Glanza V CVT'
 'Mahindra Alturas G4 4WD AT [2018-2020]' 'Renault Duster 85 PS RxL'
 'BMW 3 Series GT 320d Sport Line [2014-2016]'
 'Maruti Suzuki Ignis Alpha 1.2 MT' 'Maruti Suzuki Celerio VXi (O) CNG'
 'Ford EcoSport Signature Edition Diesel' 'Maruti Suzuki Ciaz Zeta 1.4 MT'
 'Honda Jazz VX Petrol' 'Audi Q3 35 TDI Premium Plus + Sunroof'
 'Jaguar XF 2.2 Diesel Luxury'
 'Hyundai Grand i10 Sportz 1.2 Kappa VTVT [2013-2016]'
 'Honda Amaze 1.2 S i-VTEC' 'Tata Nexon XZ Plus (O)'
 'Audi Q7 Technology 55 TFSI' 'Toyota Corolla Altis JS Petrol'
 'Mercedes-Benz E-Class E250 CDI Avantgarde'
 'Skoda Kodiaq L&K 2.0 TDI 4x4 AT' 'Skoda Octavia Elegance 1.8 TSI AT'
 'Tata Nexon XZA Plus (S)'
 'Maruti Suzuki Eeco 5 STR WITH A/C+HTR CNG [2017-2019]'
 'Mahindra Thar CRDe 4x4 Non AC' 'BMW X5 xDrive 30d M Sport'
 'BMW X5 xDrive30d xLine' 'Audi Q3 2.0 TDI quattro Premium Plus'
 'Hyundai i10 Sportz 1.2 AT Kappa2' 'Mahindra XUV300 W8 1.5 Diesel'
 'Maruti Suzuki Celerio ZXi AMT ABS' 'Hyundai Verna 1.6 VTVT S'
 'Hyundai Creta 1.6 SX' 'Hyundai Xcent S 1.1 CRDi (O)'
 'Maruti Suzuki Celerio ZXi AMT [2017-2019]' 'Honda City 1.5 S AT'
 'Renault Duster 85 PS Base 4X2 MT Diesel'
 'Maruti Suzuki Baleno Alpha Automatic'
 'Hyundai Grand i10 Asta AT 1.2 Kappa VTVT [2013-2016]'
 'Hyundai Grand i10 Asta AT 1.2 Kappa VTVT (O) [2016-2017]'
 'Maruti Suzuki Ciaz Zeta 1.4 AT' 'Tata Nexon EV XZ Plus'
 'Mahindra Quanto C8' 'Tata Tigor Buzz Petrol' 'Maruti Suzuki Dzire VXi'
 'Hyundai Tucson 2WD MT Diesel'
 'Skoda Octavia 1.8 TSI Style Plus AT [2017]'
 'Hyundai Verna SX Plus 1.6 CRDi AT' 'Hyundai Santro Xing GL Plus'
 'BMW 3 Series 320d Highline Sedan' 'Maruti Suzuki Wagon R 1.0 LXI ABS'
 'Maruti Suzuki Alto 800 VXi' 'Tata Harrier XTA Plus Dark Edition'
 'Hyundai Elite i20 Magna 1.2' 'Skoda Rapid Style 1.5 TDI'
 'Renault Kwid RXL' 'Maruti Suzuki Swift DZire ZDI'
 'Renault Kwid CLIMBER 1.0 [2017-2019]' 'Nissan Terrano XL (D)'
 'MG Hector Sharp 1.5 Petrol CVT' 'Maruti Suzuki Vitara Brezza VXi'
 'Honda Jazz S Petrol'
 'Land Rover Range Rover Velar 2.0 R-Dynamic S Petrol 250 [2017-2020]'
 'Renault Duster 110 PS RxZ Diesel' 'Maruti Suzuki Ertiga ZXi AT'
 'Renault Kwid Neotech RXL' 'Renault Captur Platine Mono Diesel'
 'Hyundai Santro Sportz AMT [2018-2020]' 'Hyundai Verna SX (O) 1.5 CRDi'
 'Mahindra XUV300 1.5 W8 (O) [2019-2020]'
 'Toyota Innova Crysta 2.8 ZX AT 7 STR [2016-2020]'
 'Ford Figo Titanium 1.5 Ti-VCT AT' 'Tata Tiago Revotron XZ Plus'
 'Volkswagen Tiguan Highline TDI' 'Toyota Camry Hybrid'
 'Honda Amaze 1.2 SX i-VTEC' 'Mercedes-Benz C-Class 250 CDI Avantagarde'
 'Fiat Punto Evo Dynamic 1.2'
 'Mercedes-Benz E-Class E 220d Exclusive [2019-2019]'
 'Audi A6 Technology 45 TFSI' 'Mahindra XUV500 W7 [2018-2020]'
 'Mercedes-Benz GLE 250 d' 'Hyundai Santro Magna [2018-2020]'
 'Maruti Suzuki Swift Dzire VXI'
 'Maruti Suzuki Celerio VXi CNG [2017-2019]'
 'Mercedes-Benz C-Class C 220 CDI Style'
 'Mahindra Thar LX Hard Top Petrol MT' 'Toyota Fortuner 4x2 AT'
 'Hyundai Grand i10 Magna 1.2 Kappa VTVT CNG [2019-2020]'
 'Maruti Suzuki Ciaz Sigma 1.4 MT' 'Honda Amaze 1.2 VX i-VTEC'
 'MG Astor Savvy 1.5 CVT S Red' 'Honda City 1.5 V MT Sunroof'
 'Maruti Suzuki Swift LXi' 'Honda Brio S MT' 'Mahindra XUV500 W10 AT'
 'Maruti Suzuki Swift Dzire ZDI AMT' 'Maruti Suzuki Dzire ZDi Plus'
 'Hyundai Creta Facelift 1.4 Turbo Petrol DCT'
 'Hyundai Elantra SX (O) 2.0 AT' 'Volkswagen Ameo Comfortline 1.0L (P)'
 'Maruti Suzuki Dzire ZXi' 'Volkswagen Vento Highline Petrol'
 'Tata Nexon XMA Petrol' 'Maruti Suzuki Vitara Brezza ZXi Plus AT SHVS'
 'Audi Q7 4.2 TDI quattro' 'Toyota Camry Hybrid [2015-2017]'
 'Tata Harrier XZA Plus Dual Tone'
 'MG Hector Sharp 1.5 Petrol Turbo Hybrid MT'
 'Maruti Suzuki Wagon R 1.0 LXi CNG' 'Maruti Suzuki Celerio VXi CNG'
 'Hyundai Creta SX 1.6 AT CRDi'
 'Maruti Suzuki Celerio X Zxi (O) AMT [2017-2019]'
 'Tata Tiago Revotron XZ' 'Ford Fiesta Exi 1.6 Duratec Ltd'
 'Maruti Suzuki Vitara Brezza ZDi'
 'Hyundai Grand i10 Sports Edition 1.1 CRDi' 'Honda BR-V V CVT Petrol'
 'Honda City V Petrol [2017-2019]' 'Tata Safari XZA Plus'
 'Renault Triber RXZ' 'BMW 7 Series 730Ld' 'Nissan Sunny XL D'
 'Land Rover Range Rover Evoque HSE Dynamic'
 'Honda Amaze 1.2 VX AT i-VTEC' 'Tata Harrier XZA Plus Dark Edition'
 'Maruti Suzuki Alto K10 LXi CNG'
 'Toyota Innova Crysta 2.4 ZX 7 STR [2016-2020]'
 'Hyundai i10 Asta 1.2 AT with Sunroof' 'Maruti Suzuki Ritz Vdi BS-IV'
 'Chevrolet Beat LS Diesel' 'Nissan Sunny XL CVT AT'
 'Hyundai Venue SX 1.4 (O) CRDi' 'Honda Brio V MT'
 'Tata Zest XM 75 PS Diesel'
 'Maruti Suzuki Celerio VXi (O) CNG [2019-2020]'
 'Renault Duster RXZ 1.3 Turbo Petrol CVT [2020-2021]'
 'Hyundai i20 Active 1.2 SX' 'Tata Nexon XZA Plus'
 'Tata Nexon XZ Plus Dual Tone' 'Maruti Suzuki Ciaz S 1.4 MT'
 'Volkswagen Polo Highline1.2L (D)' 'Toyota Yaris J CVT [2018-2020]'
 'Honda Jazz S MT [2015-2016]' 'Honda City ZX CVT Petrol [2017-2019]'
 'Toyota Etios VX' 'Nissan Magnite XV Premium Dual Tone'
 'Skoda Rapid Style 1.6 MPI AT' 'Volkswagen Cross Polo 1.2 MPI'
 'Honda City S' 'Honda Amaze VX CVT 1.2 Petrol'
 'Hyundai i10 Magna 1.1 iRDE2 [2010-2017]' 'Jaguar XE Prestige'
 'Maruti Suzuki S-Cross Zeta' 'Honda Jazz S Diesel [2015-2016]'
 'Ford EcoSport Titanium 1.5L TDCi'
 'Maruti Suzuki Vitara Brezza ZDi+ Dual Tone [2017-2018]'
 'Skoda Laura Ambition 2.0 TDI CR AT' 'Hyundai Elantra 1.6 SX AT'
 'Land Rover Discovery Sport SE' 'Maruti Suzuki Ciaz Alpha 1.4 MT'
 'Honda City ZX EXi' 'Hyundai Elite i20 Asta 1.4 CRDi'
 'Hyundai Aura SX 1.2 (O) Petrol' 'Maruti Suzuki Dzire ZXi Plus'
 'Hyundai Elite i20 Asta 1.2 (O) [2019-2020]' 'Kia Seltos GTX 1.4'
 'Renault Duster 110 PS RXS 4X2 AMT Diesel'
 'Kia Seltos HTX 1.5 [2020-2021]' 'BMW 7 Series 730Ld Sedan'
 'Kia Seltos HTX IVT 1.5 [2019-2020]'
 'Mercedes-Benz CLA 200 D Urban Sport'
 'Maruti Suzuki Swift ZXi AMT [2018-2019]' 'Mercedes-Benz GLA 200 d Sport'
 'Honda Jazz VX CVT Petrol' 'Toyota Urban Cruiser High Grade AT'
 'Hyundai Creta SX 1.6 CRDI (O)' 'Datsun GO T (O)'
 'Toyota Innova 2.5 GX BS IV 7 STR' 'Audi A8 L 3.0 TDI quattro'
 'Ford Freestyle Trend Plus 1.2 Ti-VCT [2019-2020]'
 'Tata Altroz XZ (O) Diesel' 'Mercedes-Benz S-Class 350 L'
 'Honda Jazz SV Petrol' 'Hyundai i20 Sportz 1.4 CRDI'
 'Kia Sonet HTX 1.0 iMT [2020-2021]'
 'Hyundai Eon 1.0 Kappa Magna + [2014-2016]' 'Toyota Innova 2.5 G2'
 'Maruti Suzuki Ciaz ZXi  AT' 'Mercedes-Benz E-Class 280'
 'Mercedes-Benz R-Class R350 4MATIC' 'Honda Amaze 1.5 E i-DTEC'
 'Nissan Terrano XL D Plus' 'Volkswagen Vento Highline Petrol AT'
 'Mercedes-Benz E-Class E350 CDI Avantgarde'
 'Maruti Suzuki Wagon R 1.0 LXi CNG Avance LE' 'Mahindra Marazzo M6 8 STR'
 'Datsun redi-GO Gold Limited Edition' 'Renault Kwid 1.0 RXT AMT Opt'
 'Jeep Compass Limited (O) 2.0 Diesel [2017-2020]'
 'Tata Nexon XZ Plus (S)' 'Maruti Suzuki Ciaz ZXi'
 'Kia Sonet HTE 1.2 [2020-2021]' 'Maruti Suzuki Ertiga VXI'
 'Audi A6 35 TDI Premium' 'Jeep Compass Sport 1.4 Petrol'

In [36]:
df2 = df.copy()

In [37]:
df2.dtypes

car_name               object
car_price_in_rupees    object
kms_driven             object
fuel_type              object
city                   object
year_of_manufacture     int64
dtype: object

In [38]:
# split the 'Name' column into company and model
def split_name(name_str):
    two_word_companies = ['Land Rover', 'Mercedes Benz', 'Maruti Suzuki', 'Mercedes-Benz', 'Rolls Royce', 'Mini Cooper', 'MINI Cooper']
    name_parts = name_str.split()

    if ' '.join(name_parts[:2]) in two_word_companies:
        company_name = ' '.join(name_parts[:2])
        model_name = ' '.join(name_parts[2:])
    else:
        company_name = name_parts[0]
        model_name = ' '.join(name_parts[1:])

    return pd.Series([company_name, model_name])

df2[['Company', 'Model']] = df2['car_name'].apply(split_name)
df2[['Company', 'Model']]

            Company                                       Model
0           Hyundai  Grand i10 Magna 1.2 Kappa VTVT [2017-2020]
1     Maruti Suzuki                                Alto 800 Lxi
2              Tata                          Safari XZ Plus New
3     Maruti Suzuki                                   Ciaz ZXI+
4              Jeep   Compass Sport Plus 1.4 Petrol [2019-2020]
...             ...                                         ...
2100           Ford                       Figo Titanium1.5 TDCi
2101    MINI Cooper                         Countryman Cooper D
2102        Hyundai                           Verna 1.6 VTVT SX
2103  Maruti Suzuki                                Ciaz VXi+ AT
2104        Hyundai                           Verna 1.6 VTVT SX

[2105 rows x 2 columns]

In [39]:
df2

,car_name,car_price_in_rupees,kms_driven,fuel_type,city,year_of_manufacture,Company,Model
0,Hyundai Grand i10 Magna 1.2 Kappa VTVT [2017-2...,₹ 4.45 Lakh,"22,402 km",Petrol,Mumbai,2016,Hyundai,Grand i10 Magna 1.2 Kappa VTVT [2017-2020]
1,Maruti Suzuki Alto 800 Lxi,₹ 2.93 Lakh,"10,344 km",Petrol,Kolkata,2019,Maruti Suzuki,Alto 800 Lxi
2,Tata Safari XZ Plus New,₹ 22.49 Lakh,"12,999 km",Diesel,Bangalore,2021,Tata,Safari XZ Plus New
3,Maruti Suzuki Ciaz ZXI+,₹ 6.95 Lakh,"45,000 km",Petrol,Thane,2016,Maruti Suzuki,Ciaz ZXI+
4,Jeep Compass Sport Plus 1.4 Petrol [2019-2020],₹ 12 Lakh,"11,193 km",Petrol,Kolkata,2019,Jeep,Compass Sport Plus 1.4 Petrol [2019-2020]
...,...,...,...,...,...,...,...,...
2100,Ford Figo Titanium1.5 TDCi,₹ 3.6 Lakh,"42,158 km",Diesel,Kolkata,2015,Ford,Figo Titanium1.5 TDCi
2101,MINI Cooper Countryman Cooper D,₹ 22 Lakh,"68,862 km",Diesel,Hyderabad,2013,MINI Cooper,Countryman Cooper D
2102,Hyundai Verna 1.6 VTVT SX,₹ 8.38 Lakh,"37,622 km",Petrol,Chennai,2018,Hyundai,Verna 1.6 VTVT SX
2103,Maruti Suzuki Ciaz VXi+ AT,₹ 6.75 Lakh,"64,726 km",Petrol,Mumbai,2017,Maruti Suzuki,Ciaz VXi+ AT
2104,Hyundai Verna 1.6 VTVT SX,₹ 8.76 Lakh,"29,150 km",Petrol,Pune,2017,Hyundai,Verna 1.6 VTVT SX

In [40]:
df2 = df2.drop('car_name', axis=1)

In [41]:
df2

,car_price_in_rupees,kms_driven,fuel_type,city,year_of_manufacture,Company,Model
0,₹ 4.45 Lakh,"22,402 km",Petrol,Mumbai,2016,Hyundai,Grand i10 Magna 1.2 Kappa VTVT [2017-2020]
1,₹ 2.93 Lakh,"10,344 km",Petrol,Kolkata,2019,Maruti Suzuki,Alto 800 Lxi
2,₹ 22.49 Lakh,"12,999 km",Diesel,Bangalore,2021,Tata,Safari XZ Plus New
3,₹ 6.95 Lakh,"45,000 km",Petrol,Thane,2016,Maruti Suzuki,Ciaz ZXI+
4,₹ 12 Lakh,"11,193 km",Petrol,Kolkata,2019,Jeep,Compass Sport Plus 1.4 Petrol [2019-2020]
...,...,...,...,...,...,...,...
2100,₹ 3.6 Lakh,"42,158 km",Diesel,Kolkata,2015,Ford,Figo Titanium1.5 TDCi
2101,₹ 22 Lakh,"68,862 km",Diesel,Hyderabad,2013,MINI Cooper,Countryman Cooper D
2102,₹ 8.38 Lakh,"37,622 km",Petrol,Chennai,2018,Hyundai,Verna 1.6 VTVT SX
2103,₹ 6.75 Lakh,"64,726 km",Petrol,Mumbai,2017,Maruti Suzuki,Ciaz VXi+ AT
2104,₹ 8.76 Lakh,"29,150 km",Petrol,Pune,2017,Hyundai,Verna 1.6 VTVT SX

In [42]:
print(df2['Company'].unique())

['Hyundai' 'Maruti Suzuki' 'Tata' 'Jeep' 'Toyota' 'Renault' 'Chevrolet'
 'Mercedes-Benz' 'Ford' 'Porsche' 'Kia' 'BMW' 'Honda' 'Audi' 'MG' 'Skoda'
 'Volkswagen' 'Volvo' 'Mahindra' 'Nissan' 'Land Rover' 'Isuzu' 'Jaguar'
 'MINI Cooper' 'Datsun' 'Fiat' 'Citroen' 'Bentley']

## Year_of_manufacture

In [16]:
import datetime
current_year = datetime.datetime.now().year

In [43]:
df2['Age'] = current_year - df2['year_of_manufacture']

In [44]:
df2 = df2.drop('year_of_manufacture', axis=1)

In [45]:
df2

,car_price_in_rupees,kms_driven,fuel_type,city,Company,Model,Age
0,₹ 4.45 Lakh,"22,402 km",Petrol,Mumbai,Hyundai,Grand i10 Magna 1.2 Kappa VTVT [2017-2020],9
1,₹ 2.93 Lakh,"10,344 km",Petrol,Kolkata,Maruti Suzuki,Alto 800 Lxi,6
2,₹ 22.49 Lakh,"12,999 km",Diesel,Bangalore,Tata,Safari XZ Plus New,4
3,₹ 6.95 Lakh,"45,000 km",Petrol,Thane,Maruti Suzuki,Ciaz ZXI+,9
4,₹ 12 Lakh,"11,193 km",Petrol,Kolkata,Jeep,Compass Sport Plus 1.4 Petrol [2019-2020],6
...,...,...,...,...,...,...,...
2100,₹ 3.6 Lakh,"42,158 km",Diesel,Kolkata,Ford,Figo Titanium1.5 TDCi,10
2101,₹ 22 Lakh,"68,862 km",Diesel,Hyderabad,MINI Cooper,Countryman Cooper D,12
2102,₹ 8.38 Lakh,"37,622 km",Petrol,Chennai,Hyundai,Verna 1.6 VTVT SX,7
2103,₹ 6.75 Lakh,"64,726 km",Petrol,Mumbai,Maruti Suzuki,Ciaz VXi+ AT,8
2104,₹ 8.76 Lakh,"29,150 km",Petrol,Pune,Hyundai,Verna 1.6 VTVT SX,8

## kms_driven

In [46]:
# rename the column
df2 = df2.rename(columns={'kms_driven': 'kilometers_driven'})

In [47]:
df2

,car_price_in_rupees,kilometers_driven,fuel_type,city,Company,Model,Age
0,₹ 4.45 Lakh,"22,402 km",Petrol,Mumbai,Hyundai,Grand i10 Magna 1.2 Kappa VTVT [2017-2020],9
1,₹ 2.93 Lakh,"10,344 km",Petrol,Kolkata,Maruti Suzuki,Alto 800 Lxi,6
2,₹ 22.49 Lakh,"12,999 km",Diesel,Bangalore,Tata,Safari XZ Plus New,4
3,₹ 6.95 Lakh,"45,000 km",Petrol,Thane,Maruti Suzuki,Ciaz ZXI+,9
4,₹ 12 Lakh,"11,193 km",Petrol,Kolkata,Jeep,Compass Sport Plus 1.4 Petrol [2019-2020],6
...,...,...,...,...,...,...,...
2100,₹ 3.6 Lakh,"42,158 km",Diesel,Kolkata,Ford,Figo Titanium1.5 TDCi,10
2101,₹ 22 Lakh,"68,862 km",Diesel,Hyderabad,MINI Cooper,Countryman Cooper D,12
2102,₹ 8.38 Lakh,"37,622 km",Petrol,Chennai,Hyundai,Verna 1.6 VTVT SX,7
2103,₹ 6.75 Lakh,"64,726 km",Petrol,Mumbai,Maruti Suzuki,Ciaz VXi+ AT,8
2104,₹ 8.76 Lakh,"29,150 km",Petrol,Pune,Hyundai,Verna 1.6 VTVT SX,8

In [48]:
df2['kilometers_driven'] = df2['kilometers_driven'].str.replace(' km', '', regex=False)
df2['kilometers_driven'] = df2['kilometers_driven'].str.replace(',', '')
df2['kilometers_driven'] = df2['kilometers_driven'].astype(float)

In [49]:
df2

,car_price_in_rupees,kilometers_driven,fuel_type,city,Company,Model,Age
0,₹ 4.45 Lakh,22402.0,Petrol,Mumbai,Hyundai,Grand i10 Magna 1.2 Kappa VTVT [2017-2020],9
1,₹ 2.93 Lakh,10344.0,Petrol,Kolkata,Maruti Suzuki,Alto 800 Lxi,6
2,₹ 22.49 Lakh,12999.0,Diesel,Bangalore,Tata,Safari XZ Plus New,4
3,₹ 6.95 Lakh,45000.0,Petrol,Thane,Maruti Suzuki,Ciaz ZXI+,9
4,₹ 12 Lakh,11193.0,Petrol,Kolkata,Jeep,Compass Sport Plus 1.4 Petrol [2019-2020],6
...,...,...,...,...,...,...,...
2100,₹ 3.6 Lakh,42158.0,Diesel,Kolkata,Ford,Figo Titanium1.5 TDCi,10
2101,₹ 22 Lakh,68862.0,Diesel,Hyderabad,MINI Cooper,Countryman Cooper D,12
2102,₹ 8.38 Lakh,37622.0,Petrol,Chennai,Hyundai,Verna 1.6 VTVT SX,7
2103,₹ 6.75 Lakh,64726.0,Petrol,Mumbai,Maruti Suzuki,Ciaz VXi+ AT,8
2104,₹ 8.76 Lakh,29150.0,Petrol,Pune,Hyundai,Verna 1.6 VTVT SX,8

## Fuel-type

In [50]:
print(df2['fuel_type'].unique())

['Petrol' 'Diesel' 'Diesel + 1' 'Electric' 'CNG' 'Petrol + 1' 'Hybrid'
 'LPG']

In [51]:
df2['fuel_type'].value_counts()

fuel_type
Petrol        1348
Diesel         636
CNG             82
Petrol + 1      18
Electric        10
Diesel + 1       7
Hybrid           2
LPG              2
Name: count, dtype: int64

In [52]:
df2['fuel_type'] = df2['fuel_type'].replace('Diesel + 1', 'Diesel')
df2['fuel_type'] = df2['fuel_type'].replace('Petrol + 1', 'Petrol')

In [53]:
df2['fuel_type'].value_counts()

fuel_type
Petrol      1366
Diesel       643
CNG           82
Electric      10
Hybrid         2
LPG            2
Name: count, dtype: int64

In [54]:
# finding cars with fuel_type LPG
mask = df2['fuel_type'] == 'LPG'
lpg_rows = df2[mask]
print(lpg_rows)

     car_price_in_rupees  kilometers_driven fuel_type       city  Company  \
1206          ₹ 3.5 Lakh            73380.0       LPG  Hyderabad  Hyundai
1771         ₹ 4.75 Lakh            34810.0       LPG  Bangalore  Hyundai

                                               Model  Age
1206                               i10 Magna 1.1 LPG   12
1771  Grand i10 Magna 1.0 Kappa VTVT LPG [2014-2016]   10

In [55]:
mask2 = df2['fuel_type'] == 'CNG'
cng_rows = df2[mask]
print(cng_rows)

     car_price_in_rupees  kilometers_driven fuel_type       city  Company  \
1206          ₹ 3.5 Lakh            73380.0       LPG  Hyderabad  Hyundai
1771         ₹ 4.75 Lakh            34810.0       LPG  Bangalore  Hyundai

                                               Model  Age
1206                               i10 Magna 1.1 LPG   12
1771  Grand i10 Magna 1.0 Kappa VTVT LPG [2014-2016]   10

In [56]:
mask5 = df2['fuel_type'] == 'Hybrid'
hyb_rows = df2[mask5]
print(hyb_rows)

     car_price_in_rupees  kilometers_driven fuel_type         city Company  \
735         ₹ 18.66 Lakh            32000.0    Hybrid  Pallikarnai      MG
1588         ₹ 14.5 Lakh            35000.0    Hybrid        Delhi      MG

                                           Model  Age
735      Hector Sharp 1.5 Petrol Turbo Hybrid MT    3
1588  Hector Sharp Hybrid 1.5 Petrol [2019-2020]    5

In [57]:
# replace fuel_type LPG with CNG
mask3 = df2['fuel_type'] == 'LPG'
df2.loc[mask3, 'fuel_type'] = 'CNG'

In [59]:
mask_fuel = df2['fuel_type'].isin(['CNG', 'Electric', 'Hybrid'])
df2.loc[mask_fuel, 'fuel_type'] = 'Alternative Fuel'

In [73]:
df2['fuel_type'].value_counts()

fuel_type
Petrol              1366
Diesel               643
Alternative Fuel      96
Name: count, dtype: int64

In [61]:
df2

,car_price_in_rupees,kilometers_driven,fuel_type,city,Company,Model,Age
0,₹ 4.45 Lakh,22402.0,Petrol,Mumbai,Hyundai,Grand i10 Magna 1.2 Kappa VTVT [2017-2020],9
1,₹ 2.93 Lakh,10344.0,Petrol,Kolkata,Maruti Suzuki,Alto 800 Lxi,6
2,₹ 22.49 Lakh,12999.0,Diesel,Bangalore,Tata,Safari XZ Plus New,4
3,₹ 6.95 Lakh,45000.0,Petrol,Thane,Maruti Suzuki,Ciaz ZXI+,9
4,₹ 12 Lakh,11193.0,Petrol,Kolkata,Jeep,Compass Sport Plus 1.4 Petrol [2019-2020],6
...,...,...,...,...,...,...,...
2100,₹ 3.6 Lakh,42158.0,Diesel,Kolkata,Ford,Figo Titanium1.5 TDCi,10
2101,₹ 22 Lakh,68862.0,Diesel,Hyderabad,MINI Cooper,Countryman Cooper D,12
2102,₹ 8.38 Lakh,37622.0,Petrol,Chennai,Hyundai,Verna 1.6 VTVT SX,7
2103,₹ 6.75 Lakh,64726.0,Petrol,Mumbai,Maruti Suzuki,Ciaz VXi+ AT,8
2104,₹ 8.76 Lakh,29150.0,Petrol,Pune,Hyundai,Verna 1.6 VTVT SX,8

## car_price_in_rupees

In [62]:
df2 = df2.rename(columns={'car_price_in_rupees': 'car_price'})

In [63]:
df2['car_price'] = df2['car_price'].str.replace('₹', '', regex=False)
df2['car_price'] = df2['car_price'].str.strip() # remove leading/trailing spaces

In [64]:
df2 = df2.sort_values(by=['car_price'], ascending=False)

In [65]:
def convert_car_price(price_str):
    price_str = str(price_str)
    price_str = price_str.replace(',', '')

    if 'Lakh' in price_str:
        price_str = price_str.replace(' Lakh', '')
        price = float(price_str) * 100000
    elif 'Crore' in price_str:
        price_str = price_str.replace(' Crore', '')
        price = float(price_str) * 10000000
    else:
        price = float(price_str)

    return price

In [66]:
df2['car_price'] = df2['car_price'].apply(convert_car_price)

In [67]:
df2

,car_price,kilometers_driven,fuel_type,city,Company,Model,Age
1635,99991.0,29012.0,Petrol,Kolkata,Maruti Suzuki,Estilo LXi,17
17,9500000.0,3200.0,Alternative Fuel,Pune,Mercedes-Benz,EQC 400 4MATIC,3
566,9300000.0,6500.0,Petrol,Pune,Audi,Q7 Technology 55 TFSI,3
1397,999000.0,21691.0,Petrol,Bangalore,Honda,City V,6
804,999000.0,58019.0,Petrol,Bangalore,Honda,City VX CVT Petrol,8
...,...,...,...,...,...,...,...
1850,13600000.0,36000.0,Diesel,Bangalore,Land Rover,Range Rover Sport SE 3.0 Diesel [2018-2020],6
313,12300000.0,39012.0,Diesel,Thane,Land Rover,Range Rover Sport SDV6 SE,6
1340,11900000.0,24500.0,Petrol,Kolkata,Mercedes-Benz,S-Class Maybach S 500,8
21,11500000.0,6500.0,Petrol,Pune,Porsche,718 Boxster,5
376,110000.0,18000.0,Petrol,Ahmedabad,Tata,Nano Twist XT,10

In [68]:
df2.dtypes

car_price            float64
kilometers_driven    float64
fuel_type             object
city                  object
Company               object
Model                 object
Age                    int64
dtype: object

In [69]:
max_price = df2['car_price'].max()
min_price = df2['car_price'].min()
price_range = max_price - min_price

print(f"Maximum price is : {max_price}")
print(f"Minimum price is : {min_price}")
print(f"The range of car prices is: {price_range}")

Maximum price is : 19500000.0
Minimum price is : 60000.0
The range of car prices is: 19440000.0

In [70]:
df2

,car_price,kilometers_driven,fuel_type,city,Company,Model,Age
1635,99991.0,29012.0,Petrol,Kolkata,Maruti Suzuki,Estilo LXi,17
17,9500000.0,3200.0,Alternative Fuel,Pune,Mercedes-Benz,EQC 400 4MATIC,3
566,9300000.0,6500.0,Petrol,Pune,Audi,Q7 Technology 55 TFSI,3
1397,999000.0,21691.0,Petrol,Bangalore,Honda,City V,6
804,999000.0,58019.0,Petrol,Bangalore,Honda,City VX CVT Petrol,8
...,...,...,...,...,...,...,...
1850,13600000.0,36000.0,Diesel,Bangalore,Land Rover,Range Rover Sport SE 3.0 Diesel [2018-2020],6
313,12300000.0,39012.0,Diesel,Thane,Land Rover,Range Rover Sport SDV6 SE,6
1340,11900000.0,24500.0,Petrol,Kolkata,Mercedes-Benz,S-Class Maybach S 500,8
21,11500000.0,6500.0,Petrol,Pune,Porsche,718 Boxster,5
376,110000.0,18000.0,Petrol,Ahmedabad,Tata,Nano Twist XT,10

In [71]:
unique_cities = df2['city'].unique()
city_counts = df2['city'].value_counts()

print("Unique cities:", unique_cities)
print("\nCity counts:\n", city_counts)

Unique cities: ['Kolkata' 'Pune' 'Bangalore' 'Chennai' 'Hyderabad' 'Thane' 'Delhi'
 'Ahmedabad' 'Mumbai' 'Gurgaon' 'Thiruvallur' 'Pallikarnai' 'Faridabad'
 'Noida' 'Ambattur' 'Poonamallee']

City counts:
 city
Bangalore      248
Pune           247
Ahmedabad      246
Mumbai         246
Kolkata        245
Hyderabad      245
Thane          244
Delhi          190
Chennai         78
Noida           41
Ambattur        19
Pallikarnai     17
Thiruvallur     16
Gurgaon          8
Poonamallee      8
Faridabad        7
Name: count, dtype: int64

In [72]:
df2

,car_price,kilometers_driven,fuel_type,city,Company,Model,Age
1635,99991.0,29012.0,Petrol,Kolkata,Maruti Suzuki,Estilo LXi,17
17,9500000.0,3200.0,Alternative Fuel,Pune,Mercedes-Benz,EQC 400 4MATIC,3
566,9300000.0,6500.0,Petrol,Pune,Audi,Q7 Technology 55 TFSI,3
1397,999000.0,21691.0,Petrol,Bangalore,Honda,City V,6
804,999000.0,58019.0,Petrol,Bangalore,Honda,City VX CVT Petrol,8
...,...,...,...,...,...,...,...
1850,13600000.0,36000.0,Diesel,Bangalore,Land Rover,Range Rover Sport SE 3.0 Diesel [2018-2020],6
313,12300000.0,39012.0,Diesel,Thane,Land Rover,Range Rover Sport SDV6 SE,6
1340,11900000.0,24500.0,Petrol,Kolkata,Mercedes-Benz,S-Class Maybach S 500,8
21,11500000.0,6500.0,Petrol,Pune,Porsche,718 Boxster,5
376,110000.0,18000.0,Petrol,Ahmedabad,Tata,Nano Twist XT,10

In [74]:
df2['fuel_type'].value_counts()

fuel_type
Petrol              1366
Diesel               643
Alternative Fuel      96
Name: count, dtype: int64

In [75]:
#df3['car_price'] = (df3['car_price'] - df3['car_price'].min()) / (df3['car_price'].max() - df3['car_price'].min())

In [77]:
'''
# reverting back scaling since car_price is target variable
x_min = 60000.0
x_max = 19500000.0
df3['car_price_original'] = df3['car_price'] * (x_max - x_min) + x_min
df3['car_price'] = df3['car_price_original']
df3 = df3.drop('car_price_original', axis=1)
'''

"\n# reverting back scaling since car_price is target variable\nx_min = 60000.0\nx_max = 19500000.0\ndf3['car_price_original'] = df3['car_price'] * (x_max - x_min) + x_min\ndf3['car_price'] = df3['car_price_original']\ndf3 = df3.drop('car_price_original', axis=1)\n"

In [78]:
df2

,car_price,kilometers_driven,fuel_type,city,Company,Model,Age
1635,99991.0,29012.0,Petrol,Kolkata,Maruti Suzuki,Estilo LXi,17
17,9500000.0,3200.0,Alternative Fuel,Pune,Mercedes-Benz,EQC 400 4MATIC,3
566,9300000.0,6500.0,Petrol,Pune,Audi,Q7 Technology 55 TFSI,3
1397,999000.0,21691.0,Petrol,Bangalore,Honda,City V,6
804,999000.0,58019.0,Petrol,Bangalore,Honda,City VX CVT Petrol,8
...,...,...,...,...,...,...,...
1850,13600000.0,36000.0,Diesel,Bangalore,Land Rover,Range Rover Sport SE 3.0 Diesel [2018-2020],6
313,12300000.0,39012.0,Diesel,Thane,Land Rover,Range Rover Sport SDV6 SE,6
1340,11900000.0,24500.0,Petrol,Kolkata,Mercedes-Benz,S-Class Maybach S 500,8
21,11500000.0,6500.0,Petrol,Pune,Porsche,718 Boxster,5
376,110000.0,18000.0,Petrol,Ahmedabad,Tata,Nano Twist XT,10

In [132]:
max_price = df2['kilometers_driven'].max()
min_price = df2['kilometers_driven'].min()
price_range = max_price - min_price

print(f"Maximum price is : {max_price}")
print(f"Minimum price is : {min_price}")
print(f"The range of car prices is: {price_range}")

Maximum price is : 3600000.0
Minimum price is : 64.0
The range of car prices is: 3599936.0

In [193]:
df2

,car_price,kilometers_driven,fuel_type,city,Company,Model,Age
1635,99991.0,29012.0,Petrol,Kolkata,Maruti Suzuki,Estilo LXi,17
17,9500000.0,3200.0,Alternative Fuel,Pune,Mercedes-Benz,EQC 400 4MATIC,3
566,9300000.0,6500.0,Petrol,Pune,Audi,Q7 Technology 55 TFSI,3
1397,999000.0,21691.0,Petrol,Bangalore,Honda,City V,6
804,999000.0,58019.0,Petrol,Bangalore,Honda,City VX CVT Petrol,8
...,...,...,...,...,...,...,...
1656,142000.0,46733.0,Petrol,Kolkata,Hyundai,Santro Xing GL,15
1850,13600000.0,36000.0,Diesel,Bangalore,Land Rover,Range Rover Sport SE 3.0 Diesel [2018-2020],6
313,12300000.0,39012.0,Diesel,Thane,Land Rover,Range Rover Sport SDV6 SE,6
1340,11900000.0,24500.0,Petrol,Kolkata,Mercedes-Benz,S-Class Maybach S 500,8
376,110000.0,18000.0,Petrol,Ahmedabad,Tata,Nano Twist XT,10

In [194]:
df2.to_csv('processed_data.csv', index=False)